namespace FacturXDotNet.API.Features.Generate.Models;

/// <summary>
///     Represents the models of auto-generated PDFs that can be configured within the system.
/// </summary>
public enum AutoGeneratedPdfModels
{
    /// <summary>
    ///     Represents the standard model configuration for auto-generated PDFs.
    /// </summary>
    Standard
}
