import { Component, ElementRef, inject, viewChild } from '@angular/core';
import { EditorStateService } from '../../services/editor-state.service';
import { ImportFileService } from '../../../../core/import-file/import-file.service';

@Component({
  selector: 'app-editor-import-menu',
  template: `
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle px-4 text-light" role="button" data-bs-toggle="dropdown" aria-expanded="false">Import</a>
      <ul class="dropdown-menu">
        <li>
          <a class="dropdown-item" href="javascript:void 0;">Import Cross-Industry Invoice data</a>
          <a class="dropdown-item" href="javascript:void 0;" (click)="importPdfImage()">Import PDF image</a>
        </li>
      </ul>
    </li>
  `,
})
export class EditorImportMenuComponent {
  private editorStateService = inject(EditorStateService);
  private importFileService = inject(ImportFileService);

  importPdfImage() {
    this.importFileService.importFile('.pdf').then(async (file) => {
      if (file === undefined) {
        return;
      }

      const state = this.editorStateService.savedState.value() ?? { cii: { content: {} } };
      const newState = { ...state, pdf: { name: file.name, content: file, isAutoGenerated: false } };
      await this.editorStateService.update(newState);
    });
  }
}
