profile = "custom"

[msbuild]
project = "FacturXDotNet.sln"

[msbuild.properties]
PublishTrimmed = false

[[pack]]
rid = ["win-x64", "win-arm", "win-arm64"]
kinds = ["zip"]
[[pack]]
rid = ["linux-x64", "linux-arm", "linux-arm64"]
kinds = ["deb", "tar"]
[[pack]]
rid = ["osx-x64", "osx-arm64"]
kinds = ["tar"]

# Disable builds that didn't work

# error NETSDK1083: The specified RuntimeIdentifier 'rhel-x64' is not recognized. See https://aka.ms/netsdk1083 for more information.
# [[pack]]
# rid = ["rhel-x64"]
# kinds = ["rpm", "tar"]

# error NETSDK1084: There is no application host available for the specified RuntimeIdentifier 'win-arm'.
# [[pack]]
# rid = ["win-arm"]
# kinds = ["zip"]

[coverage]
include_test_assembly = false
badge_upload_to_gist = true
badge_gist_id = "39cc9832bf323ebb2e7c25a6f0e585b7"

[github]
user = "ismailbennani"
repo = "FacturXDotNet"

[nuget]
publish_draft = true

[brew]
publish = false

[scoop]
publish = false