//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface ApplicableHeaderTradeAgreement {
    buyerReference?: string | undefined;
    sellerTradeParty?: SellerTradeParty | undefined;
    buyerTradeParty?: BuyerTradeParty | undefined;
    buyerOrderReferencedDocument?: BuyerOrderReferencedDocument | undefined;

    [key: string]: any;
}

export interface ApplicableHeaderTradeDelivery {

    [key: string]: any;
}

export interface ApplicableHeaderTradeSettlement {
    invoiceCurrencyCode?: string | undefined;
    specifiedTradeSettlementHeaderMonetarySummation?: SpecifiedTradeSettlementHeaderMonetarySummation | undefined;

    [key: string]: any;
}

export interface BuyerOrderReferencedDocument {
    issuerAssignedId?: string | undefined;

    [key: string]: any;
}

export interface BuyerTradeParty {
    name?: string | undefined;
    specifiedLegalOrganization?: BuyerTradePartySpecifiedLegalOrganization | undefined;

    [key: string]: any;
}

export interface BuyerTradePartySpecifiedLegalOrganization {
    id?: string | undefined;
    idSchemeId?: string | undefined;

    [key: string]: any;
}

export interface CrossIndustryInvoice {
    exchangedDocumentContext?: ExchangedDocumentContext | undefined;
    exchangedDocument?: ExchangedDocument | undefined;
    supplyChainTradeTransaction?: SupplyChainTradeTransaction | undefined;

    [key: string]: any;
}

export interface ExchangedDocument {
    id?: string | undefined;
    typeCode?: number | undefined;
    issueDateTime?: Date | undefined;
    issueDateTimeFormat?: number | undefined;

    [key: string]: any;
}

export interface ExchangedDocumentContext {
    businessProcessSpecifiedDocumentContextParameterId?: string | undefined;
    guidelineSpecifiedDocumentContextParameterId?: number | undefined;

    [key: string]: any;
}

export interface GenerateFacturXRequest {
    pdfFileBase64?: string;
    xmpMetadata?: XmpMetadata;
    crossIndustryInvoice?: CrossIndustryInvoice;

    [key: string]: any;
}

export interface SellerTradeParty {
    name?: string | undefined;
    specifiedLegalOrganization?: SellerTradePartySpecifiedLegalOrganization | undefined;
    postalTradeAddress?: SellerTradePartyPostalTradeAddress | undefined;
    specifiedTaxRegistration?: SellerTradePartySpecifiedTaxRegistration | undefined;

    [key: string]: any;
}

export interface SellerTradePartyPostalTradeAddress {
    countryId?: string | undefined;

    [key: string]: any;
}

export interface SellerTradePartySpecifiedLegalOrganization {
    id?: string | undefined;
    idSchemeId?: string | undefined;

    [key: string]: any;
}

export interface SellerTradePartySpecifiedTaxRegistration {
    id?: string | undefined;
    idSchemeId?: number | undefined;

    [key: string]: any;
}

export interface SpecifiedTradeSettlementHeaderMonetarySummation {
    taxBasisTotalAmount?: number | undefined;
    taxTotalAmount?: number | undefined;
    taxTotalAmountCurrencyId?: string | undefined;
    grandTotalAmount?: number | undefined;
    duePayableAmount?: number | undefined;

    [key: string]: any;
}

export interface SupplyChainTradeTransaction {
    applicableHeaderTradeAgreement?: ApplicableHeaderTradeAgreement | undefined;
    applicableHeaderTradeDelivery?: ApplicableHeaderTradeDelivery | undefined;
    applicableHeaderTradeSettlement?: ApplicableHeaderTradeSettlement | undefined;

    [key: string]: any;
}

export interface XmpBasicMetadata {
    identifier?: string[];
    createDate?: Date | undefined;
    creatorTool?: string | undefined;
    label?: string | undefined;
    metadataDate?: Date | undefined;
    modifyDate?: Date | undefined;
    rating?: number;
    baseUrl?: string | undefined;
    nickname?: string | undefined;
    thumbnails?: XmpThumbnail[];

    [key: string]: any;
}

export interface XmpDublinCoreMetadata {
    contributor?: string[];
    coverage?: string | undefined;
    creator?: string[];
    date?: Date[];
    description?: string[];
    format?: string | undefined;
    identifier?: string | undefined;
    language?: string[];
    publisher?: string[];
    relation?: string[];
    rights?: string[];
    source?: string | undefined;
    subject?: string[];
    title?: string[];
    type?: string[];

    [key: string]: any;
}

export interface XmpFacturXMetadata {
    documentFileName?: string | undefined;
    documentType?: number | undefined;
    version?: string | undefined;
    conformanceLevel?: number | undefined;

    [key: string]: any;
}

export interface XmpMetadata {
    pdfAIdentification?: XmpPdfAIdentificationMetadata | undefined;
    basic?: XmpBasicMetadata | undefined;
    pdf?: XmpPdfMetadata | undefined;
    dublinCore?: XmpDublinCoreMetadata | undefined;
    pdfAExtensions?: XmpPdfAExtensionsMetadata | undefined;
    facturX?: XmpFacturXMetadata | undefined;

    [key: string]: any;
}

export interface XmpPdfAExtensionsMetadata {
    schemas?: XmpPdfASchemaMetadata[];

    [key: string]: any;
}

export interface XmpPdfAFieldMetadata {
    description?: string | undefined;
    name?: string | undefined;
    valueType?: string | undefined;

    [key: string]: any;
}

export interface XmpPdfAIdentificationMetadata {
    amendment?: string | undefined;
    conformance?: number | undefined;
    part?: number | undefined;

    [key: string]: any;
}

export interface XmpPdfAPropertyMetadata {
    category?: number | undefined;
    description?: string | undefined;
    name?: string | undefined;
    valueType?: string | undefined;

    [key: string]: any;
}

export interface XmpPdfASchemaMetadata {
    namespaceUri?: string | undefined;
    prefix?: string | undefined;
    property?: XmpPdfAPropertyMetadata[];
    schema?: string | undefined;
    valueType?: XmpPdfATypeMetadata[];

    [key: string]: any;
}

export interface XmpPdfATypeMetadata {
    description?: string | undefined;
    field?: XmpPdfAFieldMetadata[];
    namespaceUri?: string | undefined;
    prefix?: string | undefined;
    type?: string | undefined;

    [key: string]: any;
}

export interface XmpPdfMetadata {
    keywords?: string | undefined;
    pdfVersion?: string | undefined;
    producer?: string | undefined;
    trapped?: boolean | undefined;

    [key: string]: any;
}

export interface XmpThumbnail {
    format?: number | undefined;
    height?: number | undefined;
    width?: number | undefined;
    image?: string | undefined;

    [key: string]: any;
}

export interface FileResponse {
    data: Blob;
    status: number;
    fileName?: string;
    headers?: { [name: string]: any };
}

D:\source\repos\FacturXDotNet\src\FacturXDotNet.WebEditor\src\app\core\services\api\clients\api-base.ts