profile = "custom"

[msbuild]
project = "FacturXDotNet.sln"

[msbuild.properties]
PublishTrimmed = false
AssemblyInformationalVersion = "0.0.0"

[[pack]]
rid = ["win-x64", "win-arm64"]
kinds = ["zip"]
[[pack]]
rid = ["linux-x64", "linux-arm", "linux-arm64"]
kinds = ["deb", "tar"]
[[pack]]
rid = ["osx-x64", "osx-arm64"]
kinds = ["tar"]

# Disable builds that didn't work

# error NETSDK1083: The specified RuntimeIdentifier 'rhel-x64' is not recognized. See https://aka.ms/netsdk1083 for more information.
# [[pack]]
# rid = ["rhel-x64"]
# kinds = ["rpm", "tar"]

# error NETSDK1084: There is no application host available for the specified RuntimeIdentifier 'win-arm'.
# [[pack]]
# rid = ["win-arm"]
# kinds = ["zip"]

[[changelog.autolabeler]]
label = "breaking-change"
title = '^[^:]+!:'

[[changelog.autolabeler]]
label = "maintenance"
title = '^ci:'

[[changelog.autolabeler]]
label = "documentation"
title = '^docs:'

[[changelog.autolabeler]]
label = "tests"
title = '^test:'

[[changelog.autolabeler]]
label = "examples"
title = [
    '^example:',
    '^sample:'
]

[[changelog.autolabeler]]
label = "accessibility"
title = '^access:'

[[changelog.autolabeler]]
label = "bugfix"
title = '^fix:'

[[changelog.autolabeler]]
label = "feature"
title = '^feat:'

[[changelog.autolabeler]]
label = "enhancement"
title = [
    '^refactor:',
    '^build:',
    '^perf:'
]

[[changelog.autolabeler]]
label = "dependencies"
title = '^deps:'

[[changelog.autolabeler]]
label = "skip-release-notes"
title = [
    '^Merge remote-tracking branch'
]

[[changelog.autolabeler]]
label = "misc"
title = '.'

[github]
user = "FacturX-NET"
repo = "FacturXDotNet"
version_prefix = "v"

[nuget]
publish_draft = false # no need to publish to nuget every time we push a commit to main

[brew]
publish = false

[scoop]
publish = false