name: Continuous Deployment - Publish alpha build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha'
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

concurrency:
  group: alpha
  cancel-in-progress: true

jobs:
  compute-version:
    name: Compute Version
    uses: ./.github/workflows/reusable-compute-version.yml
  
  build-api-docker-image:
    name: Build Docker Image
    needs: compute-version
    uses: ./.github/workflows/reusable-build-publish-api-docker-image.yml
    with:
      tag: latest-alpha
      version: ${{ needs.compute-version.outputs.version }}
  
  build-editor-application:
    name: Build Editor Application
    needs: compute-version
    uses: ./.github/workflows/reusable-build-editor-application.yml
    with:
      artifact-name: editor
      api-url: https://alpha.facturxdotnet.org/api
      version: ${{ needs.compute-version.outputs.version }}

  deploy-api-and-editor:
    name: Deploy API and Editor to Production
    needs:
      - build-api-docker-image
      - build-editor-application
    uses: ./.github/workflows/reusable-deploy-api-editor.yml
    with:
      editor-artifact-name: editor
      prerelease: alpha
    secrets:
      PROD_SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
      PROD_SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
      PROD_SSH_USER: ${{ secrets.PROD_SSH_USER }}