name: Continuous Deployment - Deploy Pull Request

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  remove-deployment:
    name: Remove deployment at pr${{ github.event.number }}.facturxdotnet.org
    uses: ./.github/workflows/reusable-remove-deployment.yml
    with:
      prerelease: pr${{ github.event.number }}
    secrets:
      PROD_SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
      PROD_SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
      PROD_SSH_USER: ${{ secrets.PROD_SSH_USER }}
  
  build-deploy-api-editor:
    name: Build & Deploy to pr${{ github.event.number }}.facturxdotnet.org
    uses: ./.github/workflows/reusable-build-deploy-api-editor.yml
    with:
      prerelease: pr${{ github.event.number }}
    secrets:
      PROD_SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
      PROD_SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
      PROD_SSH_USER: ${{ secrets.PROD_SSH_USER }}