name: Manual Deployment - Build & Deploy API & Editor

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: The prerelease identifier, the apps will be deployed to the PRERELEASE.facturxdotnet.org domain.
        type: string
        required: true

jobs:
  build-deploy-api-editor:
    name: Build & Deploy API & Editor
    uses: ./.github/workflows/reusable-build-deploy-api-editor.yml
    with:
      prerelease: ${{ inputs.prerelease }}
    secrets:
      PROD_SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
      PROD_SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
      PROD_SSH_USER: ${{ secrets.PROD_SSH_USER }}