name: Build & Test

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Install MinVer CLI
        run: dotnet tool install --global minver-cli

      - name: Get version
        id: get_version
        run: echo "{version}={$(minver --tag-prefix v --verbosity debug)}" >> $GITHUB_OUTPUT

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore /p:Version={{ steps.get_version.outputs.version }}

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet pack FacturXDotNet.CLI\FacturXDotNet.CLI.csproj --no-build --output nupkg --framework net10.0

      - name: Publish NuGet tool
        run: dotnet nuget push nupkg\*.nupkg --api-key "${{ secrets.NUGET_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
