name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  dotnet-releaser:
    name: Build, Test, Pack, Publish, Push
    runs-on: ubuntu-latest
    
    permissions:
      actions: write
      contents: read
      issues: read
      checks: write
      pull-requests: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Install .NET 8.0 (for dotnet-releaser)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Add System.CommandLine daily builds nuget source
        run: dotnet nuget add source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries/nuget/v3/index.json --name "System.CommandLine - Daily Builds"

      - name: Build, Tests, Cover, Pack and Publish (on push tag)
        shell: bash
        run: |
          dotnet tool install --global dotnet-releaser
          dotnet-releaser run --nuget-token "${{ secrets.NUGET_KEY }}" --github-token "${{ secrets.PAT_GITHUB_TOKEN }}" --github-token-gist "${{ secrets.PAT_GITHUB_TOKEN }}" --skip-app-packages-for-build-only dotnet-releaser.toml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            TestResults/**/*.xml
            TestResults/**/*.trx
            TestResults/**/*.json

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: artifacts-dotnet-releaser
          if-no-files-found: 'error'
