name: Release Library and Tool

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  MINVERBUILDMETADATA: build.${{ github.run_id }}.${{ github.run_attempt}}

jobs:
  dotnet-releaser:
    name: Library and Tool - Build, Test, Pack, Publish, Push
    runs-on: ubuntu-latest
    
    permissions:
      actions: write
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install MinVer
        run: dotnet tool install -g minver-cli

      - name: Compute version
        id: compute_version
        run: |
          VERSION=$(minver -t v -v d)
          echo "Version is $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set version in dotnet-releaser config file
        run: |
          sed -i "s/Version = \"0.0.0\"/Version = \"${{ steps.compute_version.outputs.version }}\"/" src/dotnet-releaser.toml

      - name: Add System.CommandLine daily builds nuget source
        run: dotnet nuget add source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries/nuget/v3/index.json --name "System.CommandLine - Daily Builds"

      - name: Build, Tests, Cover, Pack and Publish
        shell: bash
        env:
          MINVERVERSIONOVERRIDE: ${{ steps.compute_version.outputs.version }}
        run: |
          dotnet tool install --global dotnet-releaser
          cd src
          dotnet-releaser run --nuget-token "${{ secrets.NUGET_KEY }}" --github-token "${{ secrets.GITHUB_TOKEN }}" dotnet-releaser.toml

      - name: Upload binaries as artifact
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: src/artifacts-dotnet-releaser
          if-no-files-found: 'error'
