name: Reusable - Build & Deploy API & Editor

on:
  workflow_call:
    inputs:
      build-name:
        description: The name of the build, defaults to 'build'
        type: string
        required: true
      remove-old-image:
        description: If true, the previous image corresponding to this build will be removed (the one tagged latest-{build-name})
        type: boolean
        default: false

    secrets:
      PROD_SSH_KEY:
        required: true
      PROD_SSH_HOST:
        required: true
      PROD_SSH_USER:
        required: true

jobs:
  compute-version:
    name: Compute Version
    uses: ./.github/workflows/reusable-compute-version.yml
    with:
      build-name: ${{ inputs.build-name }}
  
  build-api-docker-image:
    name: Build Docker Image
    needs: compute-version
    uses: ./.github/workflows/reusable-build-publish-api-docker-image.yml
    with:
      tag: latest-${{ inputs.build-name }}
      version: ${{ needs.compute-version.outputs.version }}
      remove-old-tag: ${{ inputs.remove-old-image }}
  
  build-editor-application:
    name: Build Editor Application
    needs: compute-version
    uses: ./.github/workflows/reusable-build-editor-application.yml
    with:
      artifact-name: editor
      documentation-url: https://${{ inputs.build-name }}.facturxdotnet.org/docs
      api-url: https://${{ inputs.build-name }}.facturxdotnet.org/api
      version: ${{ needs.compute-version.outputs.version }}
  
  build-docs-application:
    name: Build Docs Application
    needs: compute-version
    uses: ./.github/workflows/reusable-build-docs-application.yml
    with:
      artifact-name: docs
      build-name: ${{ inputs.build-name }}
      api-url: https://${{ inputs.build-name }}.facturxdotnet.org/api
      editor-url: https://${{ inputs.build-name }}.facturxdotnet.org/editor
      version: ${{ needs.compute-version.outputs.version }}

  deploy:
    name: Deploy API and Editor
    needs:
      - build-api-docker-image
      - build-editor-application
      - build-docs-application
    uses: ./.github/workflows/reusable-deploy-api-editor-docs.yml
    with:
      editor-artifact-name: editor
      docs-artifact-name: docs
      build-name: ${{ inputs.build-name }}
    secrets:
      PROD_SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
      PROD_SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
      PROD_SSH_USER: ${{ secrets.PROD_SSH_USER }}