name: Reusable - Compute Version

on:
  workflow_call:
    inputs:
      build-name:
        description: The name of the build, defaults to 'build'
        type: string
        default: build

    outputs:
      version:
        description: The version of the application
        value: ${{ jobs.compute_version.outputs.version }}


env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  compute_version:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.compute_version.outputs.version }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 8 (for minver-cli)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install MinVer
        run: dotnet tool install -g minver-cli

      - name: Compute version
        id: compute_version
        env:
          MINVERBUILDMETADATA: ${{ inputs.build-name }}.${{ github.run_id }}.${{ github.run_attempt}}
        run: |
          VERSION=$(minver -t v -v d)
          echo "Version is $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT