name: Reusable - Build Docs Application

on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the artifact that will contain the build result
        type: string
        required: true
      
      version:
        description: The version of the application
        type: string
        required: true

jobs:
  build-editor-application:
    name: Build Docs Application
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
          cache-dependency-path: docs/package-lock.json

      - name: Install dependencies
        run: cd docs; npm ci

      - name: Set version number
        run: |
          sed -i -e 's/{VERSION}/${{ inputs.version }}/g' docs/src/index.md

      - name: Build
        run: cd docs; npm run build -- --base /docs/ --outDir dist/

      - name: Move assets to root
        run: |
          mv docs/dist/assets/* docs/dist
          rm -r docs/dist/assets

      - name: Upload build result
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: docs/dist/
          if-no-files-found: error