name: Reusable - Build & Deploy API & Editor

on:
  workflow_call:
    inputs:
      prerelease:
        description: The prerelease identifier, the apps will be deployed to the PRERELEASE.facturxdotnet.org domain.
        type: string
        required: true

    secrets:
      PROD_SSH_KEY:
        required: true
      PROD_SSH_HOST:
        required: true
      PROD_SSH_USER:
        required: true

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

concurrency:
  group: ${{ inputs.prerelease }}
  cancel-in-progress: true

jobs:
  compute-version:
    name: Compute Version
    uses: ./.github/workflows/reusable-compute-version.yml
  
  build-api-docker-image:
    name: Build Docker Image
    needs: compute-version
    uses: ./.github/workflows/reusable-build-publish-api-docker-image.yml
    with:
      tag: latest-${{ inputs.prerelease }}
      version: ${{ needs.compute-version.outputs.version }}
  
  build-editor-application:
    name: Build Editor Application
    needs: compute-version
    uses: ./.github/workflows/reusable-build-editor-application.yml
    with:
      artifact-name: editor
      api-url: https://${{ inputs.prerelease }}.facturxdotnet.org/api
      version: ${{ needs.compute-version.outputs.version }}

  deploy-api-and-editor:
    name: Deploy API and Editor
    needs:
      - build-api-docker-image
      - build-editor-application
    uses: ./.github/workflows/reusable-deploy-api-editor.yml
    with:
      editor-artifact-name: editor
      prerelease: ${{ inputs.prerelease }}
    secrets:
      PROD_SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
      PROD_SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
      PROD_SSH_USER: ${{ secrets.PROD_SSH_USER }}